### PR TITLE
Update config.dart

### PR DESCRIPTION
**Pull request by 10ndavis**
Was getting the following error when trying to use your package. 
image

This is due to a check in config.dart that is looking for the key 'tech_story' instead of 'techStory' as defined in the generated adr.yaml.

To verify this was the issue, I changed the adr to use the following: 

image

I think the proper solution would be to update the config to look for the proper keys, which I have done in this PR. 

The required flags are also not registering. this is due to the strict typing of a bool in the mapping of the yaml. It is assigning the keys to the values of the yaml, which are a string. We can do a simple string == 'true' check to transform it to a bool. 

image

Though, you may want a more elegant solution that has some null checks included. I'm more than happy to make that change as well, just let me know!

### CODE REVIEW

**Comment by 10ndavis** [comment]
This still results in a failure somewhere. doing some more testing and will re-create a pr.

**Comment by 10ndavis** [comment]
My issue was Pub was still using the old ADR, while my project was using my github version. Changed to using the local version so I could verify the changes are working and it is working as expected. 

As a side note, for Flutter projects, we have to run "flutter pub run adr -n" to use the version in our pubspec.yaml

**Comment by campovski** [comment]
Thank you very much for your PR! So obvious bug that I do not know how we missed it. However, the changes you made do not go in the direction of this project (namely using underscores instead of camel case for yaml files. Also, some other small changes were necessary so I just went ahead and changed them in #3. 😃

**Comment by 10ndavis** [comment]
You bet! Glad I could help.

**Pull request closed without merging**
